# ---
# dotfiles_repo: "https://github.com/hughcameron/dotfiles.git"
# dotfiles_repo_accept_hostkey: no
# dotfiles_repo_local_destination: "~/Projects/dotfiles"

# dotfiles_home: "~"
# dotfiles_files:
#   - .gitconfig
#   - .zpreztorc
#   - .zshrc
