---

- name: Show indicator lights for open applications in the Dock.
  osx_defaults:
    domain: com.apple.dock
    key: show-process-indicators
    type: bool
    value: true
  notify: Restart Dock

- name: Make Dock icons of hidden applications translucent.
  osx_defaults:
    domain: com.apple.dock
    key: showhidden
    type: bool
    value: true
  notify: Restart Dock
