---

- name: Ensure Homebrew Taps.
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items:
    - homebrew/core
    - caskroom/cask
    - caskroom/drivers
    - caskroom/fonts
    - buo/cask-upgrade

- name: Install homebrew apps.
  homebrew:
    name: "{{ item }}"
  with_items:
    -  ffmpeg
    -  git
    -  hunspell
    -  mas
    -  node
    -  proselint
    -  pyenv
    -  r
    -  sqlite
    -  tldr
    -  wget
    -  youtube-dl
    -  z

- name: Install casks.
  homebrew_cask:
    name: "{{ item }}"
  with_items:
    -  1password
    -  atom
    -  betterzip
    -  dash
    -  google-backup-and-sync
    -  google-chrome
    -  hyper
    -  insomnia
    -  nordvpn
    -  postman
    -  qlcolorcode
    -  qlimagesize
    -  qlmarkdown
    -  qlprettypatch
    -  qlstephen
    -  qlvideo
    -  quicklookase
    -  quicklook-csv
    -  quicklook-json
    -  sketch
    -  slack
    -  thingsmacsandboxhelper
    -  webpquicklook
    -  keepingyouawake
    -  font-fira-code
    -  font-camingocode
    -  font-inconsolata
    -  font-anonymice-powerline

- include_role:
    name: mas
  tags: [mas]
  vars:
    mas_apps:
      - { name: Bear, id: 1091189122 }
      - { name: Trello, id: 1278508951 }
      - { name: Pixelmator, id: 407963104 }
      - { name: Keynote, id: 409183694 }
      - { name: Pages, id: 409201541 }
      - { name: Numbers, id: 409203825 }
      - { name: Better Rename 9, id: 414209656 }
      - { name: Sip, id: 507257563 }
      - { name: Reeder, id: 880001334 }
      - { name: Things3, id: 904280696 }
    mas_upgrade_all_apps: yes

- include_role:
    name: dock
  tags: [dock]
  vars:
    dock_remove_undefined: yes
    dock_apps:
      - name: Trello
        path: /Applications/Trello.app
      - name: Slack
        path: /Applications/Slack.app
      - name: Reeder
        path: /Applications/Reeder.app
      - name: Bear
        path: /Applications/Bear.app
      - name: Things
        path: /Applications/Things3.app
      - name: Google Chrome
        path: /Applications/Google Chrome.app
      - name: Dash
        path: /Applications/Dash.app
      - name: Atom
        path: /Applications/Atom.app
