---

- name: Ensure Homebrew Taps.
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items:
    - homebrew/core
    - caskroom/cask
    - caskroom/drivers
    - caskroom/fonts
    - buo/cask-upgrade

- name: Install homebrew apps.
  homebrew:
    name: "{{ item }}"
  with_items:
    -  ansible
    -  curl
    -  docker
    -  ffmpeg
    -  git
    -  mas
    -  node
    -  sqlite
    -  tldr
    -  wget
    -  youtube-dl

- name: Install casks.
  homebrew_cask:
    name: "{{ item }}"
  with_items:
    -  1password
    -  alfred
    -  anaconda
    -  dash
    -  docker-toolbox
    -  dropbox
    -  font-anonymice-powerline
    -  font-camingocode
    -  font-codenewroman-nerd-font-mono
    -  font-fira-code
    -  font-ibm-plex
    -  font-inconsolata
    -  github
    -  google-chrome
    -  hyper
    -  insomnia
    -  keepingyouawake
    -  micro-snitch
    -  nordvpn
    -  notion
    -  qlcolorcode
    -  qlimagesize
    -  qlmarkdown
    -  qlprettypatch
    -  qlstephen
    -  qlvideo
    -  quicklook-csv
    -  quicklook-json
    -  quicklookase
    -  sketch
    -  slack
    -  tableplus
    -  the-unarchiver
    -  transmit
    -  tunnelblick
    -  visual-studio-code
    -  webpquicklook

- include_role:
    name: mas
  tags: [mas]
  vars:
    mas_apps:
      - { name: Agenda, id: 1287445660 }
      - { name: Keynote, id: 409183694 }
      - { name: Numbers, id: 409203825 }
      - { name: Pages, id: 409201541 }
      - { name: Pixelmator, id: 407963104 }
      - { name: Proxie, id: 897814548 }
      - { name: Quiver, id: 866773894 }
      - { name: Sip, id: 507257563 }
      - { name: Table Tool, id: 1122008420 }
    mas_upgrade_all_apps: yes

- include_role:
    name: dock
  tags: [dock]
  vars:
    dock_remove_undefined: yes
    dock_apps:
      - name: Messages
        path: /Applications/Messages.app
      - name: iTunes
        path: /Applications/iTunes.app
      - name: Google Chrome
        path: /Applications/Google Chrome.app
      - name: Slack
        path: /Applications/Slack.app
      - name: Agenda
        path: /Applications/Agenda.app
      - name: Dash
        path: /Applications/Dash.app
      - name: Quiver
        path: /Applications/Quiver.app
      - name: Hyper
        path: /Applications/Hyper.app
      - name: Visual Studio Code
        path: /Applications/Visual Studio Code.app